; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html
[platformio]
data_dir = data.gz

[env:esp32-2432S028R]
monitor_speed = 115200
platform = espressif32
board = esp32dev
board_build.partitions = no_ota.csv
framework = arduino
upload_speed = 921600
monitor_filters = esp32_exception_decoder
check_skip_packages = yes
extra_scripts =
	data_gzip.py
	build_release.py
lib_deps = 
	SPI
	bodmer/TFT_eSPI@^2.5.43
	bblanchon/ArduinoJson@^6.21.3
	bblanchon/StreamUtils@^1.9.0
	https://github.com/me-no-dev/ESPAsyncWebServer.git
	lvgl/lvgl@^9.1.0
	ropg/LVGL_CYD@^1.1.2
build_flags =
	-I src/ui
	-I src/core
	-I src/icons
	-D LV_CONF_SKIP
	-D LV_USE_TFT_ESPI=1
	-D LV_USE_STDLIB_MALLOC=LV_STDLIB_CLIB
	-D LV_USE_QRCODE=1
	-D LV_FONT_MONTSERRAT_10=1
	-D LV_FONT_MONTSERRAT_16=1
	-D LV_FONT_MONTSERRAT_20=1
	-D LV_FONT_MONTSERRAT_24=1
	-D LV_FONT_MONTSERRAT_28=1
	!python -c "import pathlib; print('\"-ffile-prefix-map=%%s/=\"' %% pathlib.Path.home().as_posix())"
	-DASYNCWEBSERVER_REGEX
	-DDISABLE_ALL_LIBRARY_WARNINGS
	-DUSER_SETUP_LOADED
	-DTFT_WIDTH=240
	-DTFT_HEIGHT=320
	-DTFT_MISO=12
	-DTFT_MOSI=13
	-DTFT_SCLK=14
	-DTFT_CS=15
	-DUSE_HSPI_PORT
	-DTFT_DC=2
	-DTFT_RST=-1
	-DTFT_BL=21
	-DTFT_BACKLIGHT_ON=LOW
	-DSPI_FREQUENCY=55000000
	-DSPI_READ_FREQUENCY=20000000
	-DSPI_TOUCH_FREQUENCY=2500000
	-DLOAD_GLCD
	-DLOAD_FONT2
	-DLOAD_FONT4
	-DLOAD_FONT6
	-DLOAD_FONT7
	-DLOAD_FONT8
	-DLOAD_GFXFF
	-DSMOOTH_FONT=0
	-DILI9341_2_DRIVER
	-DTFT_RGB_ORDER=TFT_BGR
	-DTFT_INVERSION_OFF
	-std=gnu++17
build_unflags =
	-std=gnu++11
